### ISSUE TITLE
Build action version mismatch of PreTeXt

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#123]
The version of PreTeXt that gets used in the Github action does not match the version for the project.  Specific output from the build below.

```
PreTeXt-CLI version: 2.3.9

PreTeXt project found in `/github/workspace`.
warning: Using CLI version 2.3.9 but project's `requirements.txt`
warning: is configured to use 2.3.4. Consider either installing
warning: CLI version 2.3.4 or running `pretext init --refresh`
warning: to update `requirements.txt` to match 2.3.9.
```

I seem to recall there was a reason for us to keep the project at 2.3.4, so the Action should probably be fixed to respect that.

**Comment by StevenClontz** [comment]
The main reason is that authoring tools are somewhat broken in 2.3.5+, but building and deploying from 2.3.9 isn't terrible. But we should keep these synced. This is an upstream issue (I need to make a PR to Jason's github action to install the specified version, not the latest version) - we'll keep this open until that's done.

**Comment by siwelwerd** [comment]
See https://github.com/siefkenj/pretext-build-action/pull/2

**Comment by siwelwerd** [comment]
@StevenClontz is this handled in the library repo?  If so, we should close this as wont-fix.  If not, we should transfer over.

**Comment by StevenClontz** [comment]
I think it may be fixed here as well now anyway, but closing either way.
