### ISSUE TITLE
Formatting of answer choices in LF3

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/precalculus#164]
I just submitted a pull request for LF3 (#163), and I need some help formatting the answer choices. They are four sageplots that are too big! How can I scale them down some, then make them appear in a 2x2 grid to prevent so much scrolling?

It's activity 3.3.8 and starts at line 300.

**Comment by siwelwerd** [comment]
I think just changing your list to `<ol marker= "A." cols="2"> ` will do the trick

**Comment by StevenClontz** [comment]
Yep.

![image](https://github.com/TeamBasedInquiryLearning/precalculus/assets/1559632/55cdacbc-a997-4b36-967d-8d5795a5cea0)

**Comment by AbbyANoble** [comment]
Thanks! I don't know why, but in my mind I was going to need to manipulate sageplots, not pretext, to get the grid!

**Comment by StevenClontz** [comment]
To be honest, I'm grateful @siwelwerd came in with that clutch suggestion, because I also was looking into that (which is possible, but less ideal - the more we author in PreTeXt proper, the more accessible our document is).

**Comment by siwelwerd** [comment]
Outside of a list context, we also have `<sbsgroup>` we can use to put plots into a grid, as in [Activity 4.6.16](https://teambasedinquirylearning.github.io/precalculus/2024/instructor/PR6.html#activity-rf-matching) 

![image](https://github.com/TeamBasedInquiryLearning/precalculus/assets/30658947/c8608539-4740-48b1-b5e7-13c498b4a2bb)
