### ISSUE TITLE
LF3 sage graph help

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/precalculus#185]
Could I get some help in these places? They are part of #184's updates.

Graphing vertical lines in sage. I'm not sure how to draw something that isn't a function! I've got the points there, but not the vertical lines.

- [Activity 3.3.11](https://teambasedinquirylearning.github.io/precalculus/2024/instructor/LF3.html#activity-lf3-fluency) part (e)
- [Activity 3.3.10](https://teambasedinquirylearning.github.io/precalculus/2024/instructor/LF3.html#activity-lf3-horiz-vert) part (c)

Also, in [Activity 3.3.8](https://teambasedinquirylearning.github.io/precalculus/2024/instructor/LF3.html#activity-lf3-point-slope) 
the answer choices on the left are showing up smaller than the answer choices on the right. How can we make those look better?

**Comment by StevenClontz** [comment]
```python
line([(2,-5), (2,5)], xmin=-5,xmax=5,ymin=-5,ymax=5)
```

![image](https://github.com/TeamBasedInquiryLearning/precalculus/assets/1559632/e81dfa1d-4308-4487-9866-0dd0f928a3cc)

Would that work?

**Comment by StevenClontz** [comment]
For the ol cols=2 thing:

https://groups.google.com/g/pretext-support/c/rGAmEbUfF0E

**Comment by siwelwerd** [comment]
I went ahead and fixed the vertical lines in merging #184, leaving this open until we can find a solution for the `@cols=2` problem.

**Comment by siwelwerd** [comment]
See [Activity 4.6.16](https://teambasedinquirylearning.github.io/precalculus/2024/PR6.html#activity-rf-matching) for an example of how we might do this with `<sbsgroup>` as suggested in the support thread.  But I actually think @AbbyANoble's code very reasonably describes what she wants as an author, and PreTeXt should be handling this correctly.

**Comment by siwelwerd** [comment]
PreTeXt is being updated to fix this: https://github.com/PreTeXtBook/pretext/pull/2160

**Comment by siwelwerd** [comment]
PreTeXt 2.4.1 was released the other day, so this appears to be fixed in the most recent deployment.

![image](https://github.com/TeamBasedInquiryLearning/precalculus/assets/30658947/210a3546-864e-4e6a-a1b7-0fcdb07bb41d)
