### ISSUE TITLE
Numbering issue

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#187]
Possible this is a `wontfix`, but at the moment there is a weird numbering in [Section LF5](https://teambasedinquirylearning.github.io/precalculus/2024/LF5.html). The numbers jump from Table 3.5.8 to Activity 3.5.10.  I think some students will wonder where is 3.5.9?

The answer is that it is hiding in an `<answer>`; see the [Instructor Version](https://teambasedinquirylearning.github.io/precalculus/2024/instructor/LF5.html#activity-lin-model-ex2-3) .  But this will not be transparent to students.

Is there any way around this, or just something we have to deal with on occasion? Here the task was for students to fill in a table, so naturally the `<answer>` contained a table.

**Comment by AbbyANoble** [comment]
Table 3.5.6 is also in an answer!

**Comment by StevenClontz** [comment]
Don't have a codespace available to check but #195 may address this.

**Comment by siwelwerd** [comment]
Looks okay to me.  I noted you removed the numbering from the table in the activity as well.  Is that what we want to put in our style guide--tables within activities (and answers) should be only in `<tabular>` and not also in `<table>` so that they don't get numbered?

**Comment by StevenClontz** [comment]
I think so. Or I need to edit the publication file to number tables differently than "slides" (activities, definitions, etc)

**Comment by siwelwerd** [comment]
I think lets go with the simple answer for now, until a use case calling for a differently numbered table presents itself.  The style guide has been amended accordingly.
