### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#230]
Having trouble tracking this down.  I think this was introduced when I merged #228 yesterday.  In the build of instructor-web, I see this

```
warning: Unable to generate some sageplot images:
warning:  'NoneType' object has no attribute 'split'
```

And then PreTeXt happily reports it was successful, and many images are broken throughout the book.  I don't see this error in the previous PR I merged (#227)--I think it was introduced by [Tonya's commit](https://github.com/TeamBasedInquiryLearning/precalculus/actions/runs/9161664759/job/25187016693).  Frustratingly, running `pretext build web` and `pretext generate` on my machine seem to work fine, so I am not able to isolate this any further.

**Comment by StevenClontz** [comment]
I don't think the NoneType thing is related to image generation. Can you link me to a broken image - at a glance I didn't see one.

**Comment by siwelwerd** [comment]
I noticed them in [Activity 3.1.10](https://teambasedinquirylearning.github.io/precalculus/2024/LF1.html#LR-3-Calculate-AROC-from-graph), but spot checking anything from the later modules they seem to be missing.

I think the 'NoneType' is a python thing trying to split an empty string.

**Comment by StevenClontz** [comment]
> I think the 'NoneType' is a python thing trying to split an empty string.

Yup I'm tackling that now. It's related to the `sage` executable, which seems related.

**Comment by StevenClontz** [comment]
For whatever reason, the Codespace doesn't have Sage installed.

**Comment by StevenClontz** [comment]
This is upstream, tracking at https://github.com/PreTeXtBook/pretext-cli/pull/729

**Comment by siwelwerd** [comment]
>For whatever reason, the Codespace doesn't have Sage installed.

Oh, is that why @AbbyANoble was having trouble with the image this morning?

**Comment by siwelwerd** [comment]
Ah, I see [this commit](https://github.com/oscarlevin/pretext-docker/commit/91f3d3a2fe568ad2e2b75672e9d19ddfd3377365) showed up between our last working build and the first broken one...  Starting to suspect Tonya is off the hook 🤣

**Comment by siwelwerd** [comment]
Just confirmed that the latest deployment has images.  Thanks to @oscarlevin for the upstream fix that took care of this.
