### ISSUE TITLE
Error when trying to compile the readiness page

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/precalculus#248]
I'm trying to update the EQ readiness page and I'm getting an error that I don't know how to fix. I changed one part of the text ("Readiness Outcome 1" to "Plot points on the coordinate plane"), pulled up CodeChat, and got the following error. 

I also got an error mentioning the pretext 2.3.4/2.4.1 mismatch, but I'm assuming that's because I ran the command to update in the terminal as Steven supplied in #240. 

   * PTX:ERROR:  the element with the @xml:id given as a subtree root ("EQ-intro") is not division that can be chunked into HTML page(s).  Quitting...
processing with /home/vscode/.ptx/xsl/pretext-html.xsl has failed

[critical: ](javascript:navigate_to_error("undefined", undefined))PTX:ERROR:  the element with the @xml:id given as a subtree root ("EQ-intro") is not division that can be chunked into HTML page(s).  Quitting...
------------------------
[critical: ](javascript:navigate_to_error("undefined", undefined))Failed to build.  Exiting...
While running pretext, the following errors occurred:

[31mcritical: [0mPTX:ERROR:  the element with the @xml:id given as a subtree root ("EQ-intro") is not division that can be chunked into HTML page(s).  Quitting...
[31mcritical: [0mFailed to build.  Exiting...
[/workspaces/precalculus/source/01-EQ/readiness.ptx:: ERROR: CodeChat renderer - unable to find the HTML output file /workspaces/precalculus/output/web/01-EQ/readiness.ptx.](javascript:navigate_to_error("/workspaces/precalculus/source/01-EQ/readiness.ptx", -1))

**Comment by StevenClontz** [comment]
If you change the file to `readiness.ptx` do you see what you need to see?

**Comment by AbbyANoble** [comment]
Not sure what you mean. That's the file I'm editing.

**Comment by StevenClontz** [comment]
Oops I meant `main.ptx`.

**Comment by StevenClontz** [comment]
Basically - `readiness.ptx` doesn't correspond to an individual page of the book, so CodeChat gets confused and doesn't know what to show. But `main.ptx` should show the chapter page which includes the readiness stuff.

**Comment by AbbyANoble** [comment]
Yep! Looks right there. Thanks!

**Comment by StevenClontz** [comment]
Now - maybe it makes sense to move the readiness stuff into `main.ptx` so it's easier to preview? @siwelwerd thoughts?

**Comment by siwelwerd** [comment]
I prefer the modular structure, let's just make sure our authors all know to switch back to `main.ptx` to preview it.

**Comment by AbbyANoble** [comment]
> Now - maybe it makes sense to move the readiness stuff into `main.ptx` so it's easier to preview? @siwelwerd thoughts?

Either way is fine with me! Since I'm just entering a bunch of links, there aren't as many spots to mess up the code. The main.ptx page is really clean as is.
