### ISSUE TITLE
Location of an aside

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/precalculus#252]
Is there a way to make the aside by [Remark 5.2.5](https://teambasedinquirylearning.github.io/precalculus/2024/instructor/EL2.html#EL2-3-6) 
line up next to the second bullet point of the remark? I tried putting it in there originally and it wasn't showing correctly.

**Comment by siwelwerd** [comment]
Accidentally pushed a fix for this to main.  Closed by https://github.com/TeamBasedInquiryLearning/precalculus/commit/19daf210c1bcc30da1362894aefb7dc156001dd5
