### ISSUE TITLE
Remove commentary stringparam

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#269]
Each build is throwing a PTX:DEPRECATE error about the old commentary string parameter:

```
    * PTX:DEPRECATE: (2024-02-16) the  commentary  string parameter has been deprecated, is no longer functional, and has no replacement.  Instead control the visibility of a "commentary" element by placing it into a component and using version support.  You likely also have related deprecation messages about that situation which are more informative.
    * --------------
```

I think since we are on 2.4.1 now, we are safe to just remove it, as we already set up the instructor component.

Should probably be a good citizen and submit an update to the [documentation](https://pretextbook.org/doc/guide/html/instructor-version-4.html), which still advises the use of this.

**Comment by StevenClontz** [comment]
PR to docs: https://github.com/PreTeXtBook/pretext/pull/2166 (thanks for the nudge Drew)

**Comment by siwelwerd** [comment]
Thanks, I went to try and do that myself but gave up when I couldn't figure out where the source for the guide actually lived.  I even looked in the guide to see if it would tell me where to propose enhancements to the guide, but I didn't see that anywhere in there... (maybe I should make a PR to add that now that I see where to do that).
