### ISSUE TITLE
Put Main Idea into Learning Outcomes for each chapter

### ISSUE THREAD

**Issue by tdegeorge** [TeamBasedInquiryLearning/precalculus#272]
I wasn't sure where to put this, but when I went to review the readiness stuff, I realized that none of us put a question or big idea in the learning outcomes box. Right now, the beginning of each chapter says "BIG IDEA for the chapter goes here, in outcomes/main.ptx" - is this something we agree on as a team?

**Comment by siwelwerd** [comment]
This duplicates #189 .  I'm fine for one person to do all of these, or for y'all to agree on them.  Check the Calculus and Linear Algebra books for an idea of what this looks like.
