### ISSUE TITLE
Observation versus <p>

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#29]
Currently there is some intro text [here](https://teambasedinquirylearning.github.io/precalculus/2024/PR1.html#p-21) 
styled as a `<p>`. This won't show up in a slides export, for example.  Should this instead be in an `<observation>`?

**Comment by StevenClontz** [comment]
+1

**Comment by siwelwerd** [comment]
Going ahead and assigning this to @tdegeorge as a straightforward first issue to fix :).

**Comment by siwelwerd** [comment]
This was closed by #52
