### ISSUE TITLE
Continuous compounding interest EL7

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#314]
Add an activity between 5.7.10 and 5.7.11 that scaffolds the idea of continuous compounding interest and develops motivation for $e$.

**Comment by siwelwerd** [comment]
Please use "activity-motivate-e" for the xml:id of this activity, or edit EL1  to fix the reference to match what you use.

**Comment by siwelwerd** [comment]
See #318, the reference in 5.1 should also be updated to point to this activity rather than the section when this is implemented.

**Comment by tdegeorge** [comment]
Oh sorry - just seeing this now. I just submitted a pull request that added an activity for this. I did not link this issue though - sorry!

**Comment by siwelwerd** [comment]
Closed by #382
