### ISSUE TITLE
Dollar signs breaking LaTeX

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#32]
Right now, a $ is used in 

https://github.com/TeamBasedInquiryLearning/precalculus/blob/983a7e260b6fbcc0b9863a8dccce420251ee681e/source/03-PR/02.ptx#L108

This seems fine in the HTML, but breaks the LaTeX.  Not finding a solution in a cursory search of the docs, but I suspect @StevenClontz knows what should be done instead.

**Comment by StevenClontz** [comment]
The issue is that `$10` isn't valid $\LaTeX$ - instead, we should write `\$10`.

**Comment by siwelwerd** [comment]
> The issue is that `$10` isn't valid LATEX - instead, we should write `\$10`.

Interesting that MathJax seems okay with invalid LATEX.  

FYI @kathypinzon if you have any other examples using $ -- be sure to escape it with a backslash as @StevenClontz mentioned.  This one is already fixed now though.

**Comment by StevenClontz** [comment]
Yep, it's nice for naive insertion of dollar amounts into equations rendered by MathJax (as long as it's not looking for dollar signs to know what math to render), but at the cost of incompatibility when copied into a proper LaTeX document.

Note that dollar signs (and percent signs, etc.) outside of math mode are fine; PreTeXt will handle those for the LaTeX/PDF conversion.

**Comment by kathypinzon** [comment]
yeah, I definitely knew that, just didn't even think about it since it was rendering fine in my preview.
