### ISSUE TITLE
Additional activity for LF5

### ISSUE THREAD

**Issue by AbbyANoble** [TeamBasedInquiryLearning/precalculus#379]
Add a new activity where someone is choosing between two options, like getting t-shirts made from two different places. Each has a fixed cost (setting up the printing) plus a cost per t-shirt. Or maybe one just has a cost per shirt but no set up fee? Ask to write the linear model for each. How much would it cost at each place for some amount of t-shirts? For what amount of t-shirts should you use company A? Company B?

**Comment by siwelwerd** [comment]
Closed by #416
