### ISSUE TITLE
Mistakes in PR3

### ISSUE THREAD

**Issue by tdegeorge** [TeamBasedInquiryLearning/precalculus#383]
As I was checking homework for this section, I noticed a few mistakes that need to be fixed (some of which I did not know how to do so I am putting them here!):

- Observation 4.3.1: Should the last sentence end with a question mark?
- Observation 4.3.4: It should say "When dealing with an improper fraction such as 32/7, it is sometimes useful to rewrite this as an integer plus a **proper** fraction..."
- Activity 4.3.5: The answer to part a is not lined up correctly in the division. 
- I don't think any of the answers with the division done out are lined up correctly....Is there a way to line them up? Just thinking it might be hard to understand especially when looking at the polynomial division.

**Comment by siwelwerd** [comment]
@tdegeorge Can you define what you mean by "lined up correctly" in long division?  What don't you like about 4.3.5(a), for example?

(Yes, there is a way to line them up as long as I can understand what alignment you are wanting)
