### ISSUE TITLE
PR4 Check It (old PR3)

### ISSUE THREAD

**Issue by kathypinzon** [TeamBasedInquiryLearning/precalculus#398]
This may change title depending on how we reorder PR, but what is written is great

https://teambasedinquirylearning.github.io/precalculus/2024/exercises/#/bank/PR4/1/

**Comment by siwelwerd** [comment]
Now that reordering has been done, please verify that this needs no changes.  If so, this can be closed.  If not, let me know what needs to be changed.

**Comment by AbbyANoble** [comment]
Yes, it looks good. We want to keep the long division as it originally was.
