### ISSUE TITLE
PreText (mis)managing .gitignore?

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#406]
Every time pretext builds, it wants to change the .gitignore, in particular by removing the last 3 lines.  It seems pretext now wants to automatically manage this file.  I'm not sure if that is the desired behavior; but if it is, then the change it wants to make to the .gitignore should go in a clean commit/PR.  If that is not the desired behavior, I think we simply need to delete the first line of the .gitignore.

**Comment by StevenClontz** [comment]
already fixed at https://github.com/TeamBasedInquiryLearning/library/blob/2c536d974a1461922f5c64caaca5ba144a285f41/.gitignore#L1 so I think we can not worry here

**Comment by StevenClontz** [comment]
Closed by #429
