### ISSUE TITLE
PR5 improvements

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#408]
PR5 is now the zeroes section.  See #386 

>discuss rational root theorem and find zeros using that and long division
> Students need to be able to find zeros of a “bigger” polynomial using some combo of rational root, or given one zero and divide, or graph to find a zero, then find the rest.
> A couple at the end about complex zeros.
>Also see comments from @AbbyANoble in #384

**Comment by kathypinzon** [comment]
see pull request #419

**Comment by siwelwerd** [comment]
This was closed by #419
