### ISSUE TITLE
EQ2: Specific Choice issue

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/precalculus#435]
> This isn't well-aligned with "Specific Choice". You could remove the alternative solution, warn students that they are just picking among the choices given, then add a remark following this activity outlining how the alternative solution could be used instead.

> But this is out of scope for this PR's goals, so I'll open an issue.

_Originally posted by @StevenClontz in https://github.com/TeamBasedInquiryLearning/precalculus/pull/432#discussion_r1691770320_

**Comment by AbbyANoble** [comment]
I'm inclined to leave as is. One of the things we learn in that section is there are different ways to set up a problem. I'd rather be direct about it than it be an aside/remark.
