### ISSUE TITLE
Add check it links

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#446]
Add a Checkit link to the bottom of each section.  Note that this can be done before the Checkit problems are written.

**Comment by AbbyANoble** [comment]
Just noticed these don't exist in calculus either. Will do that as well.

**Comment by siwelwerd** [comment]
The links should be of this form: `https://tbil.org/precalculus/preview/exercises/#/bank/EQ1/`
