### ISSUE TITLE
PR-1 tweaks

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/precalculus#90]
- In [Definition 4.1.5](https://teambasedinquirylearning.github.io/precalculus/2024/PR1.html#vertex-form-of-a-quadratic-function) , the maximum (or minimum) is referred to as a 'vertex', but the vertex is a point and the max/min is a scalar.  This probably needs to be tied back to section FN-4 once it's written
- Typo (stray 'the') in 4.1.6
- Definition 1.4.7 needs to be rewritten--'standard form' is being defined here so the phrasing 'Given the standard form...' is awkward.  Also it seems like we are redefining 'axis of symmetry'.  This feels like it should have a single geometric definition, and then note that it can be found from the vertex form or from the standard form in different ways.
- [Remark 4.1.11](https://teambasedinquirylearning.github.io/precalculus/2024/PR1.html#remark-vertex-form-of-a-quadratic-function) has a question--is this supposed to be an activity?  I feel like `<remark>`s should be statements, not questions.

**Comment by tdegeorge** [comment]
Changed the wording on both definitions so that they are more aligned with one another. 

The only thing I didn't touch is the first comment about the max and min being referred to the vertex. I think we can come back to this after FN-4 is written to see how we want to change the wording.

**Comment by siwelwerd** [comment]
I made a new issue #98 to deal with that one remaining thing later and will go ahead and merge your fix into this momentarily.

**Comment by siwelwerd** [comment]
This was implemented in #97
